// <auto-generated />
using JwtTokenApp.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JwtTokenApp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231206104558_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JwtTokenApp.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("loginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("userModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            loginId = "yogesh",
                            password = "yogesh123"
                        },
                        new
                        {
                            Id = 2,
                            loginId = "rajesh",
                            password = "rajesh123"
                        },
                        new
                        {
                            Id = 3,
                            loginId = "sudesh",
                            password = "sudesh123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
